### PR TITLE
Multi-geth integration bugfixes

### LINKED ISSUE #3: Tracking issue for multi-geth integration
From evm-rs created by [mersinvald](https://github.com/mersinvald) : etclabscore/evm-rs#20  

List of to-be-resolved issues for evm/multi-geth:

- [x] #4 
- [x] #5
- [x] #6
- [x] #7
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19

Start Date: 18 Feb 2019
Expected Duration: Unknown

### PR DESCRIPTION
**Pull request by mersinvald**
Integration into Multi-Geth and full run of ETH test suite revealed some bugs that were not caught before.

This PR fixes these bugs.

Closes #3,#4,#5,#6,#7,#8,#9,#10,#11,#12,#13,#14,#15,#16,#17,#18

### CODE REVIEW

**Comment by r8d8** [comment]
@mersinvald I would suggest to have separate PR for an issue in a future. 
It's a bit confusing to match changes to the concrete issue.

**Comment by mersinvald** [comment]
@r8d8 yes, I agree, that would be better, it's pretty hard to make sense of the full diff. Individual commits are mostly atomic to one single fix each, maybe that'll help?

**Review by jakelang — APPROVED** [review]
A bit of a complicated diff, but compared the fixes to the EIP specs and it looks good.

**Comment by jakelang** [comment]
@mersinvald can these fixes get unit tests as well?

**Comment by mersinvald** [comment]
@jakelang yeah, good idea, please make an issue for that, that's exactly what `regtests` are for.

**Review by sorpaas — APPROVED** [review]

**Pull request merged**
